apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: grpc-file-deploy
  name: grpc-file-service
  namespace: grpc
  #annotations:
  #  external-dns.alpha.kubernetes.io/hostname: file-cache-grpc-service.grpc.svc.cluster.local
spec:
  ports:
  - port: 5288
    protocol: TCP
    targetPort: 5288
    name: grpc-fs
  selector:
    app: grpc-file-deploy
  type: ClusterIP
  #externalTrafficPolicy: Local