apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-file-volume
  namespace: grpc
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/run/desktop/mnt/c/CarryCase/Venkatesh/M2c/files"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-file-claim
  namespace: grpc
spec:
  volumeName: pv-file-volume
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi